spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://127.0.0.1:6379
          database: 0
          clientName: singleRedis
          password: qwe123456