version: "3.9"
# 管理的服务
name: short_link
services:
  redis:
    restart: always
    image: redis
    hostname: redis
    container_name: redis
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis.conf
      - ./redis/data:/data:rw
      - ./redis/logs:/logs:rw
    command:
      # 执行的命令
      # mkdir /var/lib/redis &
      redis-server /etc/redis.conf

  mysql:
    restart: always
    image: mysql
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: qwe123456
      TZ: Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
